---
- name: Create tfstate backend
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ tfstate_rg_name }}"
        location: "{{ region }}"
    - name: Create storage account
      azure.azcollection.azure_rm_storageaccount:
        resource_group: "{{ tfstate_rg_name }}"
        name: "{{ tfstate_storage_account_name }}"
        location: "{{ region }}"
        account_type: "Standard_LRS"
        encryption:
          key_source: "Microsoft.Storage" #Maybe insecure? It is the default but let's be verbose
          services:
            blob:
              enabled: true
        kind: "BlobStorage"
        access_tier: "Cool"
    - name: Create blob container
      azure.azcollection.azure_rm_storageblob:
        resource_group: "{{ tfstate_rg_name }}"
        container: "{{ tfstate_container_name }}"
        storage_account_name: "{{ tfstate_storage_account_name }}"
