---
- name: Remove tfstate Resource Group
  hosts: localhost
  connection: local
  tasks:
  - name: Ensure resource group present
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{tfstate_rg_name}}"
      location: "{{region}}"
  - name: Remove blob container
    azure.azcollection.azure_rm_storageblob:
      resource_group: "{{tfstate_rg_name}}"
      container: "{{tfstate_container_name}}"
      storage_account_name: "{{tfstate_storage_account_name}}"
      state: absent
  - name: Create storage account
    azure.azcollection.azure_rm_storageaccount:
      resource_group: "{{tfstate_rg_name}}"
      name: "{{tfstate_storage_account_name}}"
      state: absent
