---
- name: Creating Terraform IoC
  hosts: localhost
  connection: local
  collections:
    - cloud.terraform
  vars:
    working_dir: runner/reference-architecture
    my_terraform_build: tf
  tasks:
    - name: Destroy Terraform Instance
      community.general.terraform:
        project_path: /{{working_dir}}/{{my_terraform_build}}
        state: absent
