---
- name: List the environment for testing purposes
  hosts: localhost
  connection: local
  tasks:
    - name: Get storage account info
      azure.azcollection.azure_rm_storageaccount_info:
        resource_group: patrick-rg
        name: patricktfstate
