---
- name: Creating terraform IoC
  hosts: localhost
  connection: local
  collections:
    - cloud.terraform
  tasks:
    - name: Pull main.tf file
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: /tf
    - name: Ensure Tfstate account is authenticated #Not sure if I'm doing this right tbh
      ansible.builtin.shell:
        cmd: export ACCOUNT_KEY=$(az storage account keys list --resource-group {{ tfstate_rg_name }} --account-name {{ tfstate_storage_account_name }} --query '[0].value' -o tsv) && export ARM_ACCESS_KEY=$ACCOUNT_KEY
    - name: Inject template vars
      ansible.builtin.template:
        src: /tf/{{ location_of_tfmain }}/main.tf.j2
        dest: /tf/{{ location_of_tfmain }}/main.tf
    - name: Initialize Terraform Provider
      community.general.terraform:
        project_path: /tf/{{ location_of_tfmain }}
        state: absent
        force_init: true
    - name: Deploy Terraform Instance
      community.general.terraform:
        project_path: /tf/{{ location_of_tfmain }}
        state: present
      register: deployed_tf
